"""empty message

Revision ID: 182d8298ffa8
Revises: 1f6911d1a1e3
Create Date: 2025-05-21 09:11:40.923804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182d8298ffa8'
down_revision = '1f6911d1a1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
